name: Build and Publish Plugins

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      CI: true  # tells Gradle not to run runMicrobot
      ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.NEXUS_USERNAME }}
      ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.NEXUS_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11' # or 11 depending on your project

      - name: Grant execute permissions to gradlew
        run: chmod +x gradlew

      - name: Build plugins
        run: ./gradlew clean build

      - name: Publish to Nexus
        run: ./gradlew publish

      - name: Create/Update GitHub Release with JARs
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          name: Latest build
          body: "Commit: ${{ github.sha }}"
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "**/build/libs/*.jar"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          enable_jekyll: false
          allow_empty_commit: true